services:
  serverside:
    build:
      context: .
      args:
        - GO_DEV_IMAGE=${GO_DEV_IMAGE}
        - GO_PROD_IMAGE=${GO_PROD_IMAGE}
      dockerfile: ./Dockerfile.dev.server
      target: dev
    container_name: serverApp
    working_dir: /workspace
    env_file:
      - "./.env"
    tty: true
    volumes:
      - ../..:/workspace:cached
    environment:
      # POSTGRES_HOST: "${POSTGRES_HOST}"
      PORT: 9995
    restart: always
    # depends_on:
    #   - postgres
    # command: ["/app/main"] <- prod用
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - container-link

networks:
  # docker-composeで勝手にデフォルトネットワークが生成される予防。（自動で全コンテナが所属するbridgeを指定）
  default:
    external: true
    name: bridge
  container-link:
    name: devcontainer-network
    driver: bridge