services:
  frontend:
    build:
      context: .
      args:
        - BUN_IMAGE=${BUN_IMAGE}
      dockerfile: ./Dockerfile.dev.front
    container_name: frontApp
    working_dir: /workspace/client
    env_file: # TODO: environmentで使うものだけを列挙したほうがよさそう
      - ../../.env
    tty: true
    volumes:
      - ../..:/workspace:cached

    restart: always
    command: /bin/sh -c "while sleep 1000; do :; done"
