services:
  frontend:
    build:
      context: .
      args:
        - BUN_IMAGE=${BUN_IMAGE}
      dockerfile: ./Dockerfile.dev.front
    container_name: frontApp
    working_dir: /workspace/client
    env_file:
      - ../../.env
    tty: true
    volumes:
      - ../..:/workspace:cached

    restart: always
    command: /bin/sh -c "while sleep 1000; do :; done"
    # networks: よくよく考えたら開発時は不要
    #   - devcontainer-network

# networks:
#   devcontainer-network:
#     external: true
