ARG GO_DEV_IMAGE

# ----- development -----

FROM ${GO_DEV_IMAGE} AS dev
WORKDIR /workspace

COPY go.mod* go.sum* ./
RUN go mod init sample/devcontainer-env-concept
RUN go mod download
COPY . .

# プロンプトを見やすくする https://zenn.dev/daifukuninja/articles/9e903808f4147d
RUN apt update && apt install git vim curl -y && apt clean

RUN echo "source /usr/share/bash-completion/completions/git" >> ~/.bashrc

WORKDIR /usr/share/bash-completion/completions

RUN curl -O https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
RUN curl -O https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
RUN chmod a+x git*.*
RUN ls -l $PWD/git*.* | awk '{print "source "$9}' >> ~/.bashrc

RUN echo "GIT_PS1_SHOWDIRTYSTATE=true" >> ~/.bashrc
RUN echo "GIT_PS1_SHOWUNTRACKEDFILES=true" >> ~/.bashrc
RUN echo "GIT_PS1_SHOWUPSTREAM=auto" >> ~/.bashrc

RUN echo 'export PS1="\[\033[01;31m\]\u\[\033[01;33m\]@\h \[\033[01;36m\]\\d \\t \[\033[01;32m\]\w \[\033[01;34m\]\$(__git_ps1 \"(%s)\") \\n\[\033[01;35m\]\\$ \[\033[00m\]"' >> ~/.bashrc

RUN go install github.com/air-verse/air@latest

#検証用にイメージ作りを繰り返し試すには遅すぎるので試すときは以下のDLはいったんコメントアウト
RUN go install github.com/sqldef/sqldef/cmd/psqldef@latest 
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

CMD ["air"]