ARG GO_VER
ARG GO_PROD_VER
FROM golang:${GO_VER} AS builder
WORKDIR /app
COPY go.mod* go.sum* ./
RUN go mod download
COPY . .

# 本番環境にあわせる
RUN GOOS=linux GOARCH=amd64 go build -o main /app/main.go

FROM --platform=linux/amd64 ${GO_PROD_VER}


WORKDIR /app
COPY --from=builder /app/main .
COPY .env .


EXPOSE 8085
CMD [ "/app/main" ]
